// Code generated by goctl. DO NOT EDIT!
// Source: demo2.proto

package server

import (
	"context"

	"demo2/demo2"
	"demo2/internal/logic"
	"demo2/internal/svc"
)

type Demo2Server struct {
	svcCtx *svc.ServiceContext
	demo2.UnimplementedDemo2Server
}

func NewDemo2Server(svcCtx *svc.ServiceContext) *Demo2Server {
	return &Demo2Server{
		svcCtx: svcCtx,
	}
}

func (s *Demo2Server) Ping(ctx context.Context, in *demo2.Request) (*demo2.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
